### PR TITLE
Fix: Using deprecated function

### LINKED ISSUE #16: Using deprecated function
**Describe the bug**

`mcrypt_create_iv` was DEPRECATED in PHP 7.1.0, and REMOVED in PHP 7.2.0. Our plugin is using `mcrypt_create_iv` so it can't be used for PHP ≥ 7.2

**Expected behavior**
WP Hammer works normally with PHP ≥ 7.2

**Environment information**
 - Other installed plugin(s) and version(s): WP Local Docker with PHP 7.4

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Description of the Change
This PR adds generate random password support for multiple PHP versions.

### Benefits

The random password generator now works with both PHP 5.6 and 7.0+.

### Verification Process

1. Run `wp ha -f users.user_pass=auto`.
2. See passwords generated successfully.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues
Closes #16

### CODE REVIEW

File: includes/formatters/users.php [hunk 1]
```diff
@@ -75,6 +75,25 @@ function user_pass( $user, $formatter ) {
 	return $user;
 }
 
+/**
+ * Generate a random password. Support both PHP 5.6 and PHP 7.0+.
+ *
+ * @return string
+ */
+function generate_random_password() {
+	$password = 'password';
```
Comment (ivankruchkoff) [inline includes/formatters/users.php]: Why do we set a default password here?

What scenario would we have where both function_exists( 'random_bytes' ) is false and function_exists( 'mcrypt_create_iv' )  is false?

**Review by ivankruchkoff — CHANGES_REQUESTED** [review]

File: includes/formatters/users.php (hunk 1 above)
Comment (dinhtungdu) [reply includes/formatters/users.php]: There isn't any. This is an unnecessary safety step, a fix is incoming.

**Review by ivankruchkoff — APPROVED** [review]
